### ISSUE TITLE
Run cryodrgn using subtracted particles

### ISSUE THREAD

**Issue by helgepat** [ml-struct-bio/cryodrgn#105]
Hi,

I just finished my first cryodrgn run on a ribosome dataset and I was wondering if it is possible to restrict the region of interest using subtracted particles (e. g. from Relion) instead of full ribosomes. I am asking because when I look at the initial volumes from the kmeans20 folder, I can see that there is mostly difference in the L1 stalk and not in my ligand. I know from subsorting in Relion that the ligand is quite heterogeneous, but it does not seem to be detected by cryodrgn.

Many regards,
Helge

**Comment by zhonge** [comment]
Can you share the command that you ran? I'm curious about the architecture settings you used -- thanks!

**Comment by helgepat** [comment]
I extracted my ~460k particles from Relion in a 256px box with pixelsize 1.26 and then downsampled to 128px using cryodrgn.

The commands I ran for the initial model are:

> cryodrgn preprocess job735_Bx256.mrcs -D 128 -o job735_Bx128.mrcs

> cryodrgn train_vae data/job735_Bx128.ft.txt --preprocessed --ctf data/ctf.pkl --poses data/poses.pkl --zdim 8 -n 50 -o output/00_vae128 --multigpu --load output/00_vae128/weights.1.pkl > 2022-01-31_vae128c.log
