### ISSUE TITLE
Vectorize rotation matrix computation

### ISSUE THREAD

**Issue by vineetbansal** [ml-struct-bio/cryodrgn#143]
I think the following operation can be vectorized instead of doing a list comprehension on every triple of Euler angles:

https://github.com/zhonge/cryodrgn/blob/f47871be81be2547938de7bde7d750f563afdb3f/cryodrgn/commands/parse_pose_star.py#L46

**Comment by michal-g** [comment]
As of v3.4.1 we are still using the list comprehension here:
https://github.com/ml-struct-bio/cryodrgn/blob/94f0e059a79759246f59997eec136935ccc5f642/cryodrgn/commands/parse_pose_star.py#L71-L76

Isolating the runtime of just the `rot = np.asarray([utils.R_from_relion(*x) for x in euler])` line yields times of 2.84s when applied to a particle stack of 253k images and 14.45s when applied to a larger stack of 1.27M images.

A lazy vectorization of this using
```
rot = np.apply_along_axis(utils.R_from_relion2, axis=1, arr=euler)
```
and
```
def R_from_relion2(v: np.ndarray) -> np.ndarray:
    a, b, y = v
    ...
```
actually slowed down runtimes to 3.06s and 15.26s respectively!

Instead we try:
```
rot = utils.R_from_relion(euler)
```
with
```
def R_from_relion(euler: np.ndarray) -> np.ndarray:
    """Produce a rotation matrix from Euler angles returned by RELION."""

    a = euler[:, 0] * np.pi / 180.0
    b = euler[:, 1] * np.pi / 180.0
    y = euler[:, 2] * np.pi / 180.0
    nsamp = euler.shape[0]
    ca, sa = np.cos(a), np.sin(a)
    cb, sb = np.cos(b), np.sin(b)
    cy, sy = np.cos(y), np.sin(y)

    r_amat = np.array(
        [
            [ca, -sa, np.repeat(0, nsamp)],
            [sa, ca, np.repeat(0, nsamp)],
            [np.repeat(0, nsamp), np.repeat(0, nsamp), np.repeat(1, nsamp)],
        ],
    )
    r_bmat = np.array(
        [
            [cb, np.repeat(0, nsamp), -sb],
            [np.repeat(0, nsamp), np.repeat(1, nsamp), np.repeat(0, nsamp)],
            [sb, np.repeat(0, nsamp), cb],
        ]
    )
    r_ymat = np.array(
        [
            [cy, -sy, np.repeat(0, nsamp)],
            [sy, cy, np.repeat(0, nsamp)],
            [np.repeat(0, nsamp), np.repeat(0, nsamp), np.repeat(1, nsamp)],
        ]
    )

    rmat = np.matmul(np.matmul(r_ymat.T, r_bmat.T), r_amat.T)
    rmat[:, 0, 2] *= -1
    rmat[:, 2, 0] *= -1
    rmat[:, 1, 2] *= -1
    rmat[:, 2, 1] *= -1

    return rmat
```

which successfully speeds us down to 0.22s (while keeping outputs identical) in the n_images=1.27M case! 

This change will be implemented for v3.4.2 and is available now through our beta release channel:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ 'cryodrgn<=3.4.2' --pre
```
