### ISSUE TITLE
`cryodrgn analyze` should auto-fill the epoch number in notebook

### ISSUE THREAD

**Issue by adamlerer** [ml-struct-bio/cryodrgn#171]
The epoch number is in the call to `analyze` and could be copied into the notebook automatically with a find/replace.

**Comment by vineetbansal** [comment]
Right now the `analyze` command is simply copying a template, which its able to do by relying on the fact that commands leading up to that point would have generated files and folders with names just as it wants.

If we're going to "fill-in" values in the generated notebook(s), I'd propose adding `jinja2` as a dependency so we can do this most cleanly with variable substitutions and simple templating. Let me know if this would be acceptable.

BTW, if my PR #168 can be merged in I can work on this one.

**Comment by michal-g** [comment]
I have ended up implementing this for the epoch and also kmeans numbers in `v3.3.x` with a more hacky approach by applying the standard Python string `.replace()` method to the contents of the notebook cell after it has been copied:
```
with open(nb_outfile, "r") as f:
    filter_ntbook = nbformat.read(f, as_version=nbformat.NO_CONVERT)

for cell in filter_ntbook["cells"]:
    cell["source"] = cell["source"].replace("EPOCH = None", f"EPOCH = {epoch}")
    cell["source"] = cell["source"].replace(
        "KMEANS = None", f"KMEANS = {args.ksample}"
    )

with open(nb_outfile, "w") as f:
    nbformat.write(filter_ntbook, f)
```

This relies on the fact that the string `EPOCH = None` (and `KMEANS = None`) won't show up in the notebook template other than where we are initially declaring these variables, so this substitution should be both safe and comprehensive. If we plan doing any more on-the-fly customization of the notebook templates we should nevertheless consider what @vineetbansal suggested above about using a template library like `jinja2`!
