### ISSUE TITLE
Replace cupy.fft with torch.fft

### ISSUE THREAD

**Issue by adamlerer** [ml-struct-bio/cryodrgn#201]
Someone contributed a fix that speeds up numpy fft by a ton (>100x) by moving it from numpy to cupy. That's awesome, but has some downsides:
1. Adds a dependency on cupy
2. Adds a lot of ugliness in the code to handle both the case where cupy is and isn't installed.

It turns out that there's a `torch.fft` module that we can use instead, that's actually >2x faster than cupy and will always be installed (since cryodrgn uses `torch` extensively). Lets switch to that instead.

Here's my benchmarking code:

```
import torch
import numpy as np
import cupy as cp
import time

x = np.random.rand(128, 128, 128)
np.fft.fft2(x, axes=(-1, -2))
tic = time.time()
for i in range(100):
    np.fft.fft2(x, axes=(-1, -2))
print(f"np {time.time() - tic}")

x = cp.random.rand(128, 128, 128)
cp.fft.fft2(x, axes=(-1, -2))
tic = time.time()
for i in range(100):
    cp.fft.fft2(x, axes=(-1, -2))
print(f"cp {time.time() - tic}")


x = torch.randn(128, 128, 128)
torch.fft.fft2(x, dim=(-1, -2))
tic = time.time()
for i in range(100):
    torch.fft.fft2(x, dim=(-1, -2))
print(f"torch cpu {time.time() - tic}")

x = torch.randn(128, 128, 128, device="cuda")
torch.fft.fft2(x, dim=(-1, -2))
tic = time.time()
for i in range(100):
    torch.fft.fft2(x, dim=(-1, -2))
print(f"torch gpu {time.time() - tic}")
```

Results:

```
np 4.138299942016602
cp 0.005791425704956055
torch cpu 3.473188877105713
torch gpu 0.0022153854370117188
```

**Comment by adamlerer** [comment]
Oh yeah P.S. the cupy checks are implemented incorrectly so I don't think it's even doing the fft with cupy even if you have it.

**Comment by michal-g** [comment]
As of v3.x all FFT operations have been implemented using `torch.fft`; see the module `cryodrgn.fft` for details.
