### ISSUE TITLE
Select based on UMAP values without jupyter notebook

### ISSUE THREAD

**Issue by olibclarke** [ml-struct-bio/cryodrgn#256]
Hi, for filtering after `train_vae` it is recommended to use the jupyter notebook, but this often fails/crashes for large datasets.

Is it possible via `cryodrgn_utils` or other command line approach to gate based on the UMAP values, after consulting the plots generated by `cryodrgn analyze`?

E.g. in the attached plot, I would like to select everything with UMAP2>0, UMAP1 between 0 and 10, to exclude the small population of outliers circled in red.

Cheers
Oli

<img width="386" alt="image" src="https://user-images.githubusercontent.com/19766818/227808008-955b1174-35e1-4b7f-89cf-2b138698be6d.png">

**Comment by adriangzlz97** [comment]
Hi @olibclarke,

See if my comment in #89 or my pull request help you with this #313.

**Comment by michal-g** [comment]
Closing as we have already addressed this in #313 as noted above, and discussed at #89. Note also that `cryodrgn filter`, introduced due to #323 in `v3.1.0-b`, may also work better in your case!
