### ISSUE TITLE
cryoDRGN_filtering.ipynb runs with errors

### ISSUE THREAD

**Issue by almagor** [ml-struct-bio/cryodrgn#265]
Hi,

I am a new user with Cryodgn, trying to follow the cryoDRGN EMPIAR-10076 tutorial before applying it to my own data. I have completed the initial training and now I am at the step for Particle filtering with the cryoDRGN Jupyter notebook (step 6). I was able to successfully access the Jupyter Notebook and loaded  ryoDRGN_filtering.ipynb. I changed the number of epochs to 49 in the third cell as instructed and now I understand i need to run all the cells in order (until "Filtering by clustering"). The problem is that when I run the first cell I get an error:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-15e30ee2d5f0> in <module>
>       5 import os, sys
>       6 
> ----> 7 from cryodrgn import analysis
>       8 from cryodrgn import utils
>       9 from cryodrgn import dataset
> 
> ModuleNotFoundError: No module named 'cryodrgn'
> 

Then in box 6:

> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-6-e43eb1178149> in <module>
>       1 # Load UMAP
> ----> 2 umap = utils.load_pkl(f'{WORKDIR}/analyze.{EPOCH}/umap.pkl')
>       3 # or run UMAP
>       4 # umap = analysis.run_umap(z)
> 
> NameError: name 'utils' is not defined

And more errors in boxes 7,  and 12-27.

I am using cryoDRGN version 1.1.2.dev116+g149b035, and Jupyter 4.4.0 installed by Sbgrid.

Please let me know if there is a possible fix or if a mistake was done by me in the process is generating these errors.

Thanks
Lior

**Comment by Guillawme** [comment]
The first error you get (`ModuleNotFoundError: No module named 'cryodrgn'`) suggests that you might be trying to run the notebook outside of the environment where cryoDRGN is installed. If you installed cryoDRGN with conda, as recommended, make sure you activate the correct conda environment before trying to run the notebook (`conda activate cryodrgn`).

If you followed the installation directions from the cryoDRGN documentation, you should have Jupyter already in the conda environment where cryoDRGN was installed, so you should not need the one installed by Sbgrid (which is most likely in a different environment, therefore unaware of where cryoDRGN is installed).

**Comment by almagor** [comment]
Thank you,
I followed the instructions and (with few more troubleshooting) it works now
