### ISSUE TITLE
testing/unittest.sh doesn't work

### ISSUE THREAD

**Issue by adamlerer** [ml-struct-bio/cryodrgn#267]
**Describe the bug**
I can grab a random command from `unittest.sh`

`cryodrgn train_nn data/toy_projections.mrcs --poses data/toy_angles.pkl -o output/toy_recon --domain hartley -n 2`

I get this error:

```
cryodrgn train_nn data/toy_projections.mrcs --poses data/toy_angles.pkl -o output/toy_recon --domain hartley -n 2
...
Traceback (most recent call last):
  File "/home/al1398/.conda/envs/cryodrgn1/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn', 'console_scripts', 'cryodrgn')())
  File "/home/al1398/cryodrgn/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/al1398/cryodrgn/cryodrgn/commands/train_nn.py", line 479, in main
    assert (D - 1) % 8 == 0, "Image size must be divisible by 8 for AMP training"
AssertionError: Image size must be divisible by 8 for AMP training
```

**Comment by michal-g** [comment]
In `v3.3.1` we are removing this specific error, instead throwing a warning if using AMP and encountering inputs not multiples of 8.

There are other tests in `unittest.sh` (and `testing/`) that need to be updated for new APIs, and merged with the newer `pytest` tests under `tests/` which are used for continuous integration testing. For example, for `train_nn`, the corresponding updated tests can be found in `tests/test_integration` and `tests/test_reconstruction`.

Although I can run most of the commands in `unittest` without issues, this is still a work-in-progress, and I will leave this issue open for now to track our work in getting the old tests under control!
