### ISSUE TITLE
Clean up testing scripts

### ISSUE THREAD

**Issue by Icecream-blue-sky** [ml-struct-bio/cryodrgn#27]
Since you have renamed the "lib-python" folder to "cryodrgn" which is a local library, you forget to change it in the code under testing folder.
Like in /testing/test_entropy.py
```python
sys.path.insert(0,'../lib-python')
import lie_tools
```
Though it is a small problem, it can be a little annoying...

**Comment by michal-g** [comment]
As of v3.0.0 we have cleaned up these self-referential import statements across the package, including testing scripts, with the above example now looking like:
```
from cryodrgn import lie_tools
```

See the `tool.setuptools.packages.find` entry in the `pyproject.toml` root file for how the library structure of the cryoDRGN package is defined!
