### ISSUE TITLE
cryodrgn searching for files in the wrong directory

### ISSUE THREAD

**Issue by irintom** [ml-struct-bio/cryodrgn#299]
I recently updated the cryodrgn to 2.3.1 and now cryodrgn fails to downsample the images. Basically, it is checking for the files in the wrong directory. For example in the below given case, J2615 and J2614 are in the same parent directory P8. Yet it is checking for directory J2614 inside J2615.

(cryodrgn) irin@puma:/data/cryoEM/irin/cryodrgn-IT$ cryodrgn downsample /data/cryoEM/irin/HK/P8/J2615/J2615_004_particles.cs --datadir /data/cryoEM/irin/HK/P8/ -D 128 -o /data/cryoEM/irin/cryodrgn-IT/J2615/J2615_particles.128.mrcs > J2615-downsample.txt

Traceback (most recent call last):
  File "/home/irin/miniconda3/envs/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/downsample.py", line 89, in main
    old = ImageSource.from_file(args.mrcs, lazy=lazy, indices=ind, datadir=args.datadir)
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/source.py", line 76, in from_file
    return CsSource(
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/source.py", line 422, in __init__
    super().__init__(
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/source.py", line 326, in __init__
    D = MRCFileSource(self.df["__mrc_filepath"][0]).D
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/source.py", line 235, in __init__
    header = MRCHeader.parse(filepath)
  File "/home/irin/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/mrc.py", line 104, in parse
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/cryoEM/irin/HK/P8/J2615/J2614/subtracted_particles_A_0.mrcs'

**Comment by zhonge** [comment]
I would use the latest release which is **version 2.3.0**. Can you confirm that this works for 2.3.0? 

I believe this is a bug in our latest data loading refactor which we have fixed for the next official release. Thanks for reporting this though -- we can update the top of tree in the repo.

**Comment by irintom** [comment]
Dear Dr. Zhong

Thanks for getting back to me
My PI has installed *version 2.3.1 *on her account and interestingly, it
works perfectly without any issue for her. I did the installation as per
the tutorial given online (
https://zhonge.github.io/cryodrgn/pages/installation.html#install-cryodrgn)
and for me the issue happens. I tried installing *version 2.3.0 and **version
2.2.0*.However, I ran into errors

      LookupError: setuptools-scm was unable to detect version for
/home/irin/cryodrgn2/cryodrgn-2.3.0.



      Make sure you're either building from a fully intact git repository
or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git
checkout without the .git folder) don't contain the necessary metadata and
will not work.



      For example, if you're using pip, instead of
https://github.com/user/proj/archive/master.zip use git+
https://github.com/user/proj.git#egg=proj

      [end of output]



  *note*: This error originates from a subprocess, and is likely not a
problem with pip.

*error*: *subprocess-exited-with-error*


× Getting requirements to build wheel did not run successfully.

│ exit code: *1*

╰─> See above for output.



Thanks

Irin

**Comment by michal-g** [comment]
Hi Irin, this is an issue you can run into if the code for the package was downloaded incorrectly — did you use `pip install` to get cryoDRGN, or `git clone`? (the link to the original instructions is now broken)

I will close this issue for now, but please let us know if you are still running into problems with downsampling using the latest version!
