### ISSUE TITLE
AttributeError: module 'cryodrgn.dataset' has no attribute 'load_particles'

### ISSUE THREAD

**Issue by shashi-skd** [ml-struct-bio/cryodrgn#310]
Hi,
I am running cryoDRGN 3.0.0b0 for particle filtering using Jupyter-notebook. During the execution of cell of #load input particles, I encountered the following error:
**AttributeError: module 'cryodrgn.dataset' has no attribute 'load_particles'**
I searched around the cryoDRGN module but did not find anything (function or any relevant information) related to load_particles.

Please let me know if anything that can helpful in this regard. @zhonge 
Thanks in anticipation.

![Screenshot from 2023-10-10 13-08-27](https://github.com/ml-struct-bio/cryodrgn/assets/68693325/a88f3279-39da-40cf-bc1d-f256002d507e)

**Comment by zhonge** [comment]
Thanks for reporting, we will fix this! We made some API changes to the data loading and forgot to update the jupyter notebook.

**Comment by shashi-skd** [comment]
Thanks for the information. Although I solved this after downgrading the CryoDRGN version from 3.0.b0 to 2.3.0.

**Comment by zhonge** [comment]
Fixed in v3.0.1-beta release
