### ISSUE TITLE
Pin matplotlib version to avoid the use of deprecated draw_all in Colorbar objects

### ISSUE THREAD

**Issue by schavesgm** [ml-struct-bio/cryodrgn#312]
**Describe the bug**
cryoDRGN does not specify any required version of matplotlib in the `pyproject.toml` file. As a result, a clean installation of the package will try to install the latest version. However, matplotlib deprecated in [version 3.6 ](https://matplotlib.org/3.7.3/api/colorbar_api.html#matplotlib.colorbar.Colorbar.draw_all) the `draw_all` method on `Colorbar` objects in favour of `draw_without_rendering`. This method is used in `cryodrgn analyze` to generate the jupyter notebooks.

**To Reproduce**
What is the command you used?
`cryodrgn analyze` on a clean installation of cryoDRGN should raise this bug, as matplotlib's 3.8 version would be installed.

**Expected behavior**
A simple solution for this bug would be to pin matplotlib's version to 3.6, which should not break anything. Another approach would be to pin matplotlib to 3.8 and modify any calls to `draw_all` in `Colorbar` objects.

**Comment by michal-g** [comment]
I was able to reproduce the error and fixed it by specifying `matplotlib<3.7` under `pyproject.toml` `dependencies`. We'll update this in the next release!

If you haven't done so already, you can fix this in your own installation in the meantime by editing `pyproject.toml` yourself if you are installing from source, or using `conda install matplotlib<3.7`, which will also work if you are installing using `pip`.

**Comment by michal-g** [comment]
We added pinning of the matplotlib version in the v3.0.1-beta to address this issue.
