### ISSUE TITLE
TypeError: TiltEncoder.forward() missing 1 required positional argument: 'x_tilt' during cryodrgn vae_train

### ISSUE THREAD

**Issue by Dendooventom** [ml-struct-bio/cryodrgn#317]
Hi there,

I am running cryoDRGN 3.0b for sub-tomogram particles series from M and running into the error below during vae training.

**The command:**
(cryodrgn) bash-4.4$ cryodrgn train_vae binned_MRCS/particles.mrcs --ctf ctf.pkl --poses pose.pkl --encode-mode tilt --zdim 8 -n 50 --beta .025 -o train_vae_output --v

**The output:**
(INFO) (train_vae.py) (07-Nov-23 21:53:44) /lmb/home/tdendooven/mambaforge/envs/cryodrgn/bin/cryodrgn train_vae binned_MRCS/particles.mrcs --ctf ctf.pkl --poses pose.pkl --encode-mode tilt --zdim 8 -n 50 --beta .025 -o train_vae_output --v
(INFO) (train_vae.py) (07-Nov-23 21:53:44) Namespace(particles='/cephfs2/tdendooven/hsperm/cryoDRGN/binned_MRCS/particles.mrcs', outdir='/cephfs2/tdendooven/hsperm/cryoDRGN/train_vae_output', zdim=8, poses='/cephfs2/tdendooven/hsperm/cryoDRGN/pose.pkl', ctf='/cephfs2/tdendooven/hsperm/cryoDRGN/ctf.pkl', load=None, checkpoint=1, log_interval=1000, verbose=True, seed=95726, ind=None, invert_data=True, window=True, window_r=0.85, datadir=None, lazy=False, preprocessed=False, num_workers_per_gpu=4, max_threads=16, tilt=None, tilt_deg=45, num_epochs=50, batch_size=8, wd=0, lr=0.0001, beta='.025', beta_control=None, norm=None, amp=True, multigpu=False, do_pose_sgd=False, pretrain=1, emb_type='quat', pose_lr=0.0003, qlayers=3, qdim=1024, encode_mode='tilt', enc_mask=None, use_real=False, players=3, pdim=1024, pe_type='gaussian', feat_sigma=0.5, pe_dim=None, domain='fourier', activation='relu', func=<function main at 0x1462ffc16170>)
(INFO) (train_vae.py) (07-Nov-23 21:53:45) Use cuda True
(INFO) (train_vae.py) (07-Nov-23 21:53:45) Loading dataset from /cephfs2/tdendooven/hsperm/cryoDRGN/binned_MRCS/particles.mrcs
(INFO) (dataset.py) (07-Nov-23 21:53:49) Loaded 121440 128x128 images
(INFO) (dataset.py) (07-Nov-23 21:53:49) Windowing images with radius 0.85
(INFO) (dataset.py) (07-Nov-23 21:53:50) Computing FFT
(INFO) (dataset.py) (07-Nov-23 21:53:50) Spawning 16 processes
(INFO) (dataset.py) (07-Nov-23 21:54:34) Symmetrizing image data
(INFO) (dataset.py) (07-Nov-23 21:54:45) Normalized HT by 0 +/- 208.21084594726562
(INFO) (train_vae.py) (07-Nov-23 21:54:45) Loading ctf params from /cephfs2/tdendooven/hsperm/cryoDRGN/ctf.pkl
(INFO) (ctf.py) (07-Nov-23 21:54:45) Image size (pix)  : 128
(INFO) (ctf.py) (07-Nov-23 21:54:45) A/pix             : 5.50124979019165
(INFO) (ctf.py) (07-Nov-23 21:54:45) DefocusU (A)      : 22477.099609375
(INFO) (ctf.py) (07-Nov-23 21:54:45) DefocusV (A)      : 21738.5
(INFO) (ctf.py) (07-Nov-23 21:54:45) Dfang (deg)       : 12.0
(INFO) (ctf.py) (07-Nov-23 21:54:45) voltage (kV)      : 300.0
(INFO) (ctf.py) (07-Nov-23 21:54:45) cs (mm)           : 2.700000047683716
(INFO) (ctf.py) (07-Nov-23 21:54:45) w                 : 0.10000000149011612
(INFO) (ctf.py) (07-Nov-23 21:54:45) Phase shift (deg) : 0.0
(INFO) (train_vae.py) (07-Nov-23 21:54:46) HetOnlyVAE(
  (encoder): TiltEncoder(
    (encoder1): ResidLinearMLP(
      (main): Sequential(
        (0): MyLinear(in_features=12852, out_features=1024, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
      )
    )
    (encoder2): ResidLinearMLP(
      (main): Sequential(
        (0): MyLinear(in_features=2048, out_features=1024, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
        (5): ReLU()
        (6): MyLinear(in_features=1024, out_features=16, bias=True)
      )
    )
  )
  (decoder): FTPositionalDecoder(
    (decoder): ResidLinearMLP(
      (main): Sequential(
        (0): MyLinear(in_features=392, out_features=1024, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
        (5): ReLU()
        (6): ResidLinear(
          (linear): MyLinear(in_features=1024, out_features=1024, bias=True)
        )
        (7): ReLU()
        (8): MyLinear(in_features=1024, out_features=2, bias=True)
      )
    )
  )
)
(INFO) (train_vae.py) (07-Nov-23 21:54:46) 23027730 parameters in model
(INFO) (train_vae.py) (07-Nov-23 21:54:46) 19474448 parameters in encoder
(INFO) (train_vae.py) (07-Nov-23 21:54:46) 3553282 parameters in decoder
(WARNING) (utils.py) (07-Nov-23 21:54:46) Warning: /cephfs2/tdendooven/hsperm/cryoDRGN/train_vae_output/config.yaml already exists. Overwriting.
(WARNING) (train_vae.py) (07-Nov-23 21:54:46) Warning: Masked input image dimension is not a mutiple of 8 -- AMP training speedup is not optimized
Traceback (most recent call last):
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/commands/train_vae.py", line 836, in main
    loss, gen_loss, kld = train_batch(
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/commands/train_vae.py", line 328, in train_batch
    z_mu, z_logvar, z, y_recon, y_recon_tilt, mask = run_batch(
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/commands/train_vae.py", line 387, in run_batch
    z_mu, z_logvar = _model.encode(*input_)
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/models.py", line 139, in encode
    z = self.encoder(*img)
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lmb/home/tdendooven/mambaforge/envs/cryodrgn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: TiltEncoder.forward() missing 1 required positional argument: 'x_tilt'

I am not sure if this is a bug or whether I am doing something wrong, every step up until this point worked, including the backprojection sanity check. 

Many thanks for your help,
Tom

**Comment by zhonge** [comment]
It looks like you might be using an earlier version of cryodrgn, which has reconstruction from tilt series pairs implemented. Could you double-check your cryodrgn version?

The input particles to cryoDRGN-ET should be a .star file of the 2D particle tilts exported from Warp/M with the `_rlnGroupName` column so that we know the mapping from tilt to particle. I believe `--dose-per-tilt` or (`-d`) is also a required argument for subtomogram data. If these flags are missing from `cryodrgn train_vae -h`, then it isn't the right version of cryodrgn.

**Comment by Dendooventom** [comment]
Hi Ellen,

Yes apologies, I still had an older version of cryoDRGN installed, all fixed now. 

Many thanks!
Tom
