### ISSUE TITLE
Numpy version bug with cryoDRGN-ET tilt series dataset containing variable number of tilts

### ISSUE THREAD

**Issue by zhonge** [ml-struct-bio/cryodrgn#318]
There is a bug when loading a star file containing a variable number of tilts (for cryoDRGN-ET). We tracked this down to a deprecated behavior in later versions of numpy (e.g. 1.24.4). The code works with previous versions of numpy (e.g. 1.22.3).

The error looks something like this:

```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (118025,) + inhomogeneous part.
```

This will be fixed in the next patch release.

**Comment by michal-g** [comment]
solved by pinning to an earlier version of `numpy` in `pyproject.toml` as of #331
