### ISSUE TITLE
--preprocessed flag is gone in 3.0.1b0 train_vae

### ISSUE THREAD

**Issue by azazellochg** [ml-struct-bio/cryodrgn#319]
**Describe the bug**
--preprocessed flag looks removed from train_vae command. What is the recommended workflow for preprocessed data then? I cannot run cryodrgn without this flag as input mrcs now has an uneven 65px box instead of 64px (after preprocessing). 

Is preprocessing going to be removed from the workflow (https://github.com/ml-struct-bio/cryodrgn/pull/279)?

In 2.3.0 the flag still exists and works.

**Comment by michal-g** [comment]
`--preprocessed` is indeed deprecated as of `v3.0.0-b` as we have incorporated these processing steps required to fit large datasets into memory into the commands used to train models themselves. Thus now e.g. `train_vae` by default behaves in an analogous manner to `train_vae --preprocessed ...` under the old setup, with no need to run an extra command beforehand. You should still use `--lazy` for special loading of especially large datasets.

If you have data that had been preprocessed using `cryodrgn preprocess` and you still want to use it, you can still use cryoDRGN commands from `v2.3.0` and below, or just use the original data as the input using `v3.0.0-b` and above!
