### ISSUE TITLE
Getting error when trying to analyze

### ISSUE THREAD

**Issue by RajShekhorRoy** [ml-struct-bio/cryodrgn#322]
I compiled the cryodrgn from the github source, then I was running the program as the tutorial did (https://ez-lab.gitbook.io/cryodrgn/cryodrgn-empiar-10076-tutorial). I followed it to the letter and then after training vae successfully, I tried to run the analyze to get the volumes and got an error. 

One more thing, I checked the drive and found 20 models by the name vol_00.mrc ,.... and so on. So are those the final output or it gets through some more refinement?

I ran the analyze command.
command provided : cryodrgn analyze ./EXPERIMENTS/10076/tutorial.log/ 49 --flip --Apix 3.275

I get the following error:  
home/rsr3gt/anaconda3/lib/python3.8/site-packages/cryodrgn/commands/analyze.py:315: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(4, 4))
Traceback (most recent call last):
  File "/home/rsr3gt/anaconda3/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/rsr3gt/anaconda3/lib/python3.8/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/rsr3gt/anaconda3/lib/python3.8/site-packages/cryodrgn/commands/analyze.py", line 402, in main
    analyze_zN(
  File "/home/rsr3gt/anaconda3/lib/python3.8/site-packages/cryodrgn/commands/analyze.py", line 328, in analyze_zN
    g = sns.jointplot(
TypeError: jointplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by michal-g** [comment]
Hi, can you double-check that the directory you are pointing `analyze` at contains the output of a trained model? That is, `./EXPERIMENTS/10076/tutorial.log/` should contain files like `weights.0.pkl`, `weights.10.pkl`, `...` — it should be the same directory you used for the `-o` flag when running `cryodrgn train_vae` (and not the log).

Assuming you are looking in e.g. `analyze.49/pc1` to find the `.mrc` files: these are indeed one of the final outputs of this analysis, as we sample from the latent space identified in training to generate these volumes. The Background section of the tutorial provides a brief explanation of how this sampling is done:

> Specifically, the cryodrgn analyze pipeline will produce 1) N density maps sampled from different regions of the latent space (N=20, by default), 2) continuous trajectories along the principal components axes of the latent space embeddings, and 3) visualizations of the latent space with PCA and UMAP.

You can choose to do more refinement if these volumes indicate the training was insufficient, e.g. by continuing the training process with more epochs, see "extending or restarting from a checkpoint" in the tutorial.

**Comment by zhonge** [comment]
This looks like we have a deprecated usage of `sns.jointplot`. I think we need to convert the positional arguments of the x and y data to keyword arguments `sns.jointplot(x=xdata,y=ydata,...)`

**Comment by RajShekhorRoy** [comment]
Hi,
I also think it is a problem of the sns.jointplot. I did check the directory, and it contains the weight.pkl  files .

**Comment by michal-g** [comment]
I was able to reproduce this error with seaborn v0.12 and v0.13 but the code worked fine with v0.11 — it was definitely the deprecated usage. Although we have pinned the seaborn package to `<0.12` in our installation dependencies (see `pyproject.toml`), I have updated the signatures of `sns.jointplot` as of #331 to reflect the new usage which is more Pythonic in any case. You may want to double-check the seaborn version used in your environment as it could cause other issues down the line!
