### ISSUE TITLE
cryodrgn_utils write_star should default to relion 3.1 format

### ISSUE THREAD

**Issue by zhonge** [ml-struct-bio/cryodrgn#324]
`cryodrgn_utils write_star` should write out .star files in relion 3.1 format instead of 3.0. There are also some additional column names that are needed for reimport to cryoSPARC.

**Comment by michal-g** [comment]
As of #344 we have implemented this, allowing users to go back to 3.0 if they wish using the `--relion30` flag. Additional columns added are: `_rlnImageSize`,  `_rlnImagePixelSize`, and `_rlnOpticsGroup`.
