### ISSUE TITLE
ModuleNotFoundError: No module named 'cryodrgn.source'

### ISSUE THREAD

**Issue by siayouyang** [ml-struct-bio/cryodrgn#332]
**Describe the bug**
following your examplestep 7 in nature protocols, showing:
Traceback (most recent call last):
  File "/data2/xyy/cryodrgn_test/cryodrgn/utils/analyze_convergence.py", line 26, in <module>
    from cryodrgn.source import ImageSource
ModuleNotFoundError: No module named 'cryodrgn.source'

**To Reproduce**
python cryodrgn/utils/analyze_convergence.py 01_128_8D_256 49

**Comment by siayouyang** [comment]
what I have tried:
1. activate and re-activate cryodrgn anvironment;
2. pip install ImageSource

**Comment by michal-g** [comment]
As Guillawme discussed above, you should double-check your environment, and especially the version of cryoDRGN you have installed using `cryodrgn --version`. `cryodrgn.source` is indeed a relatively new module, having been introduced in v3.0.0, so I would guess that you have v2.3.0 installed — I will add some documentation to the `analyze_convergence` script to clarify the version compatibility of this script.

Also a reminder that v3.0.0 is not available via `pip` and must be installed from source code:

```
git clone https://github.com/ml-struct-bio/cryodrgn
cd cryodrgn
pip install .
```

Just to clarify, what seems to be missing here is the module `cryodrgn.source`, not the class `ImageSource` within it, you should only have to use `pip install cryodrgn`:

> activate and re-activate cryodrgn environment;
> pip install ImageSource

**Comment by siayouyang** [comment]
> As Guillawme discussed above, you should double-check your environment, and especially the version of cryoDRGN you have installed using `cryodrgn --version`. `cryodrgn.source` is indeed a relatively new module, having been introduced in v3.0.0, so I would guess that you have v2.3.0 installed — I will add some documentation to the `analyze_convergence` script to clarify the version compatibility of this script.
> 
> Also a reminder that v3.0.0 is not available via `pip` and must be installed from source code:
> 
> ```
> git clone https://github.com/ml-struct-bio/cryodrgn
> cd cryodrgn
> pip install .
> ```
> 
> Just to clarify, what seems to be missing here is the module `cryodrgn.source`, not the class `ImageSource` within it, you should only have to use `pip install cryodrgn`:
> 
> > activate and re-activate cryodrgn environment;
> > pip install ImageSource

Very thanks to your reply! I have checked the version is indeed 2.3.0, I will reinstall and try again.

**Comment by siayouyang** [comment]
problem solved, thanks to your team!
