### ISSUE TITLE
cryodrgn analyze TBB and colorbar errors

### ISSUE THREAD

**Issue by amitrox** [ml-struct-bio/cryodrgn#339]
At the end of cryodrgn analyze, the following happens where I get issues with the TBB version (which I already updated) and the colorbar attribute. I saw in previous threads to download matplotlib 3.6.0 which I did, but that did not change the output. The result of these errors seems to be the files cryoDRGN_figures.ipynb, cryoDRGN_filtering.ipynb, and cryoDRGN_viz.ipynb not generating. The other files from cryodrgn analyze are still generated. This is what I see:

(INFO) (eval_vol.py) (22-Jan-24 11:11:06) Finished in 0:00:08.772175
(INFO) (analyze.py) (22-Jan-24 11:11:06) Running UMAP...
/home/.local/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)
(WARNING) (utils.py) (22-Jan-24 11:12:28) Warning: /home/Downloads/data/00_vae128/analyze.49/umap.pkl already exists. Overwriting.
(INFO) (analyze.py) (22-Jan-24 11:12:28) Generating plots...
/home/.local/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/.local/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/.local/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/.local/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
Traceback (most recent call last):
  File "/home/.local/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.10/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/.local/lib/python3.10/site-packages/cryodrgn/commands/analyze.py", line 385, in main
    analyze_zN(
  File "/home/.local/lib/python3.10/site-packages/cryodrgn/commands/analyze.py", line 250, in analyze_zN
    analysis.scatter_color(
  File "/home/.local/lib/python3.10/site-packages/cryodrgn/analysis.py", line 337, in scatter_color
    cbar.draw_all()
AttributeError: 'Colorbar' object has no attribute 'draw_all'. Did you mean: '_draw_all'?

Any ideas on how to fix this?

**Comment by michal-g** [comment]
Can you double-check that matplotlib v3.6 is installed, not just downloaded? I can only replicate this error with v3.8, but not v3.7 or v3.6. It would also be helpful if you shared the `analyze` command you are running, and which version of cryoDRGN you have installed.

**Comment by amitrox** [comment]
I think it's installed, because when I run "pip install matplotlib==3.6.0 I get: 
Requirement already satisfied: six>=1.5 in /home/anaconda3/envs/cryodrgn3/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib==3.6.0) (1.16.0).

I am just doing the tutorial, so the command was:  cryodrgn analyze 00_vae128 49 --flip --Apix 3.275
The cryoDRGN version is 2.3.0.

Thanks!

**Comment by michal-g** [comment]
Can you try installing the latest cryoDRGN release into an empty environment? This should both ensure that the right version of matplotlib is installed and that the code is updated:

```
git clone --depth 1 --branch v3.1.0-beta git@github.com:ml-struct-bio/cryodrgn.git
cd cryodrgn
pip install .
```

You can also check which version of matplotlib you have installed directly in a python session opened in your environment:

```
$ python
>>> import matplotlib
>>> matplotlib.__version__
```

Finally, I recommend you look into using conda to manage your Python package environments if you haven't done so already — dealing with dependency installations across many packages using only pip can get cumbersome very quickly!

**Comment by AssmannG** [comment]
FYI, I just installed it with matplotlib v3.8 , and I changed the function `cbar.draw_all` to `cbar._draw_all`, which fixed the problem.
