### ISSUE TITLE
tutorial cryosparc file cannot be parsed

### ISSUE THREAD

**Issue by azazellochg** [ml-struct-bio/cryodrgn#340]
**Describe the bug**
cryodrgn 3.1.0 beta from github
https://ez-lab.gitbook.io/cryodrgn/cryodrgn-empiar-10076-tutorial
https://github.com/zhonge/cryodrgn_empiar/blob/main/empiar10076/inputs/cryosparc_P4_J33_004_particles.cs file cannot be parsed. Error:
```
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/cryodrgn-3.1.0/bin/cryodrgn", line 8, in <module>
sys.exit(main())
File "/lmb/home/gsharov/soft/cryodrgn/cryodrgn/__main__.py", line 74, in main
args.func(args)
File "/lmb/home/gsharov/soft/cryodrgn/cryodrgn/commands/parse_pose_csparc.py", line 39, in main
data = np.load(args.input)
File "/public/EM/Scipion/miniconda3/envs/cryodrgn-3.1.0/lib/python3.10/site-packages/numpy/lib/npyio.py", line 462, in load
raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

**To Reproduce**
`cryodrgn parse_pose_csparc cryosparc_P4_J33_004_particles.cs -D 320 -o poses.pkl`

parse_ctf_csparc does not work either. I assume the cryosparc format might have changed over time and the parser accepts only newer cryosparc files?

**Comment by michal-g** [comment]
This command should still work, and indeed still does on my end with the same input file using a fresh install of cryoDRGN v3.1.0-b into both Python 3.9 and 3.10 environments. I've also tried different numpy versions to make sure that the behaviour  of the `allow_pickle` argument isn't responsible, as our use of `np.load()` here for parsing cryosparc files has remained unchanged for a long while.

Can you please double-check the input file you are using, and also the version of `numpy` you have installed just in case?

**Comment by azazellochg** [comment]
numpy                     1.22.4
python                    3.10.13

I'm using https://github.com/zhonge/cryodrgn_empiar/blob/main/empiar10076/inputs/cryosparc_P4_J33_004_particles.cs file

**Comment by azazellochg** [comment]
ah, I found the reason, I was downloading a text file..... should use https://github.com/zhonge/cryodrgn_empiar/raw/main/empiar10076/inputs/cryosparc_P4_J33_004_particles.cs instead :facepalm:

**Comment by michal-g** [comment]
thanks for the update — we should perhaps add better checking of the file type here to produce less cryptic error messages!
