### ISSUE TITLE
Interactive visualization not working

### ISSUE THREAD

**Issue by lainahall** [ml-struct-bio/cryodrgn#341]
![Screenshot 2024-01-29 at 2 58 27 PM](https://github.com/ml-struct-bio/cryodrgn/assets/153857389/598816d0-2bcd-484d-9653-8ae6d2af5575)

**Comment by michal-g** [comment]
Hi, as of `v3.1.0-b` we are offering an alternative to the widget in this notebook via the `cryodrgn filter` command. This is described in greater detail at #323 — in the future, please consider checking existing issues before opening a new one to help us out!

A reminder that the easiest method for installing this version of cryoDRGN is directly from the source code:

```
git clone git@github.com:ml-struct-bio/cryodrgn.git --depth=1 --branch=v3.1.0-beta
cd cryodrgn/
pip install .
```

This feature is still in beta so any feedback on functionality or bugs is appreciated!
