### ISSUE TITLE
abinit_homo issue with input star file

### ISSUE THREAD

**Issue by azazellochg** [ml-struct-bio/cryodrgn#343]
cryodrgn 3.1.0 beta from github

It appears that abinit_homo is missing --datadir option, while abinit_hetero and train_vae have it. This leads to an error as cryodrgn cannot find mrcs stack from the input star file.

Example command:
```
source /public/EM/Scipion/conda.rc&& conda activate cryodrgn-3.1.0 && CUDA_VISIBLE_DEVICES=0 cryodrgn abinit_homo Runs/000344_CryoDrgnProtAbinitio/extra/input_particles.star --ctf Runs/000344_CryoDrgnProtAbinitio/extra/ctf.pkl -o Runs/000344_CryoDrgnProtAbinitio/extra/output -n 5 --t-extent 2 --ps-freq 1
```

Error:
```
00020:   FileNotFoundError: [Errno 2] No such file or directory: '/....../Runs/000344_CryoDrgnProtAbinitio/extra/particles.64.0.mrcs'
```

The star file points to 000001@Runs/000344_CryoDrgnProtAbinitio/extra/input/particles.64.0.mrcs, so I need to pass `--datadir Runs/000344_CryoDrgnProtAbinitio/extra/input` somehow

**Comment by michal-g** [comment]
Yup this is definitely a problem, we will fix this in an upcoming release! In the meantime, you can either move the mrcs stack to the same location as the star file, or edit the file locations directly in the star file.
