### ISSUE TITLE
Minor bug in default beta value 

### ISSUE THREAD

**Issue by zhonge** [ml-struct-bio/cryodrgn#356]
Starting in version 3.x-beta, the default value of beta weight on the KL loss in `cryodrgn train_vae` was set to `1/ntilts` instead of `1/zdim`. We should revert back to the `1/zdim` default. 

In practice, this probably has minimal impact since the default value of ntilts=10 and zdim=8, so the default beta value was 0.1 instead of 0.125.

**Comment by michal-g** [comment]
Reverted back to the `1/zdim` default as of #344!
