### ISSUE TITLE
cryodrgn_utils filter_star missing optics table RELION 3.1 

### ISSUE THREAD

**Issue by ryanfeathers** [ml-struct-bio/cryodrgn#370]
`cryodrgn_utils filter_star` does not return an optics table when run on RELION 3.1 format star files.

Expected output: A star file containing `data_optics` and `data_particles` blocks

**Comment by michal-g** [comment]
This functionality has been added in `v3.3.3-rc0`, with the new optics table only having the optics groups present in the new filtered dataset:

https://github.com/ml-struct-bio/cryodrgn/blob/bbf144097c2214d94ef5456272d3d4cc65da3498/cryodrgn/commands_utils/filter_star.py#L53-59

Furthermore, in the case of output into separate micrograph files using `-m`, each file's optics table only contains the optics groups present for the corresponding micrograph:

https://github.com/ml-struct-bio/cryodrgn/blob/bbf144097c2214d94ef5456272d3d4cc65da3498/cryodrgn/commands_utils/filter_star.py#L73-80
