### ISSUE TITLE
Why dose the hand-vol.mrc not look like a hand?

### ISSUE THREAD

**Issue by Sumching** [ml-struct-bio/cryodrgn#375]
When  I use Chimera to visualize the hand-vol.mrc file, it look like this:

![image](https://github.com/ml-struct-bio/cryodrgn/assets/34994554/501b4310-85b5-4afd-9b4c-7719b9470f67)

Also, I resconstructed a volume from the files hand.mrcs and display it, it does not look like a hand.

If possible, can I craft a hand-shape toy example on my own?

**Comment by michal-g** [comment]
Sorry for the confusion, the file `testing/data/hand-vol.mrc` is meant for testing reference purposes and is not supposed to resemble any final reconstruction output! We will add a README to our testing materials soon to clarify this.

Can you please share the command that you used to reconstruct from `testing/data/hand.mrcs` so I can try to rerun on my end?

**Comment by Sumching** [comment]
I ran the reconstruction command found at the following link: https://github.com/ml-struct-bio/cryodrgn/blob/main/testing/unittest.sh#L23. It seems that we can use the file 'hand.mrcs' to construct a model of a hand. Could you please provide the reference volume for the hand shape, or explain how to create  a toy example with a specific shape?"

**Comment by michal-g** [comment]
Unfortunately we are still struggling a bit with finding a toy dataset to include in the package that is both small enough to not make installation cumbersome, and big enough to produce a high-quality reconstruction. For example, the full `hand.mrcs` is `782Mb` — I can provide a DropBox link to it, and share it with a particular email address, but including it in the repository is impractical at this point.

By the way the given command is only meant as a smoke test and is not intended to produce a reconstruction!

**Comment by Sumching** [comment]
Thank you! My personal email is sumching@gmail.com. This will be very helpful.

**Comment by zhonge** [comment]
Weird... did hand-vol.mrc get corrupted at some point? spike-vol.mrc also looks totally corrupted. 

<img width="360" alt="image" src="https://github.com/ml-struct-bio/cryodrgn/assets/5461028/ec9a4e65-86cf-4c7d-ab27-12fe1abbbd47">

**Comment by zhonge** [comment]
Ah, it looks like it was never added to the GitHub repo since, as Michal said, this was just used for testing. The volume is about 1Mb and can be sent if Michal hasn't already. Thanks!

**Comment by michal-g** [comment]
I created a folder for viewing/downloading the particles and the poses for `hand` here: https://www.dropbox.com/scl/fo/bvfqwm9kb42k98kerpvky/AL8ZMSjF9HnUaBwGMQMYryk?rlkey=1pzdeg34vm1cup8c1xbp9nqxg&st=w56hom1s&dl=0

Will add the reference volume and some example commands shortly!
