### ISSUE TITLE
the checkpoints of the relevant experiments

### ISSUE THREAD

**Issue by Rich-XGK** [ml-struct-bio/cryodrgn#378]
I would like to ask if there is a place where I can download the checkpoints of the relevant experiments in the paper.

**Comment by michal-g** [comment]
Hi, as outlined under the [Data availability](https://www.nature.com/articles/s41592-020-01049-4#data-availability) section of the paper, the outputs of the relevant experiments can be found under the given Zenodo links, e.g. https://zenodo.org/records/4355284. For model checkpoints, look for files labelled `weights.x.pkl`, where `x` is the label of a training epoch.

Hope that helps!
-Mike
