### ISSUE TITLE
Run.log

### ISSUE THREAD

**Issue by debanjanamaji** [ml-struct-bio/cryodrgn#393]
Hello,

I have been trying to run the `abinit_het` program. 
I used zdim = 4  and ran for 60 epochs but somehow, the run.log is somehow not updating, but I have the weights, poses and z pkl files. As a result, I can't see the learning curve. 
What might be going wrong?

**Comment by michal-g** [comment]
We have previously seen (unfortunately as yet unresolved) issues with seemingly corrupted `run.log` files — see e.g. #346 — do you see anything in your `run.log`, or is it empty? If you run this command using a cluster submission command such as `sbatch`, is there anything in the log files for this command?

**Comment by debanjanamaji** [comment]
Hello,

I reran the program, it seemingly is writing the epochs now, albeit a bit slow. 

In the previous run, only the 1st epoch was written in the run.log.

Also the previous cluster submission gave the following error 
`/mnt/home/dmaji/miniconda3/envs/cryodrgn-env/lib/python3.9/site-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]`

Is there something I might do?

**Comment by michal-g** [comment]
Sorry, do you mean that it's slow running the program, or that it's slow in writing the epoch data? That's not an error by the way, just a warning, and not something that by itself would halt the execution of the reconstruction!
