### ISSUE TITLE
Import particles from cryoSPARC

### ISSUE THREAD

**Issue by awfully-silent** [ml-struct-bio/cryodrgn#412]
This may be dumb, but how exactly can I downsample particles from a cryoSPARC refinement job in cryoDRGN for subsequent training and analysis? I kept getting an error saying "FileNotFoundError: [Errno 2] No such file or directory: ' '"

Basically I first when to the refinement job in CS, then clicked export job, and ran the cryodrgn downsample command on the Jxx_particles_exported.cs file. I also tried to supply a directory using --datadir to the exported folder containing the .cs file and micrographs etc.. I have also tried to convert the .cs file to .star using pyem, then changed all the paths in .star to absolute path, but it still didn't work. 

Thank you very much.

**Comment by michal-g** [comment]
Hey, sorry for the confusion, but this is likely due to the bug described at #408, which was fixed as of v3.4.1: `pip install 'cryodrgn==3.4.1'` — but please let us know if you still get this error with the new version!

**Comment by awfully-silent** [comment]
Hi, thank you for the response. I updated cryodrgn like you suggested and it no longer gives the same error. However there is now a new issue: I used the --chunk 50000 option for downsampling, and since I have ~180k particles, there should be four mrcs files generated. I got a warning saying "Passed header arguments {'chunksize': 5000} to 'write_mrc' but these will  not be used as header was also given!'. Then it says "Killed", and only the xx.0.mrcs file was generated, with no .txt file either. Am I not supposed to use the --chunk option anymore? Thank you again.

**Comment by awfully-silent** [comment]
Hi, I actually reran the command without any --chunk, and this time I didn't get any error.. Not sure what's the reason. Thank you.

**Comment by michal-g** [comment]
I dug into what was going on with `downsample` and discovered that batch processing was not being correctly used in the case of giving the `--chunk` argument after a refactor applied in v3.4.0, which was likely causing the out-of-memory issue you ran into above, and also the `Passed header arguments {'chunksize': 5000}` warning message.

I have applied a fix that addresses this which will be made part of the v3.4.2 release and is in the meantime available through our beta release channel:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ 'cryodrgn<=3.4.2' --pre
```

Please let us know if you run into any other problems!

-Mike
