### ISSUE TITLE
Minor typo in train_vae logger message on AMP

### ISSUE THREAD

**Issue by alkinkaz** [ml-struct-bio/cryodrgn#422]
mutiple -> multiple

https://github.com/ml-struct-bio/cryodrgn/blob/196365d3e396688c2aa03d8e1b68cd9de6e517ec/cryodrgn/commands/train_vae.py#L855

**Comment by michal-g** [comment]
Fixed this in `train_vae` and also `abinit_het` as of v3.4.3, thanks for the tip!
