### ISSUE TITLE
viz,ipynb No UMAP Table shown

### ISSUE THREAD

**Issue by EB-kim** [ml-struct-bio/cryodrgn#58]
Hi, Elllen, 
I have download croydrgn locally on linux and I ran the cryoDRGN viz.ipynb but the UMAP Tables are not shown.  I am also getting a value error eventhough I changed it, just like in the tutorial.
![image](https://user-images.githubusercontent.com/72215385/116978744-1726f880-acff-11eb-99c1-f36d54186339.png)
![image](https://user-images.githubusercontent.com/72215385/116978809-2d34b900-acff-11eb-8a74-3ad68e043b85.png)
![image](https://user-images.githubusercontent.com/72215385/116978868-3e7dc580-acff-11eb-949a-84e3e7586f17.png)

**Comment by Guillawme** [comment]
Hello,

Does it work if you use `jupyter lab` instead of `jupyter notebook`? The latest installation instructions assume you are using `jupyter lab`, and the notebook files have not been tested (at least not by me) with `jupyter notebook`.

**Comment by EB-kim** [comment]
I tried to use Jupyter lab but it doesn't work. It states that jupyter lab is not in the file.

**Comment by EB-kim** [comment]
I tried to download jupyter lab with pip install but it is not working

**Comment by Guillawme** [comment]
Installing Jupyter and Python programs like cryoDRGN typically involves many dependencies, that don't always work well with one another, making it often difficult to troubleshoot problems.

With this little information, it is impossible to help you in a more specific way than this: create a new conda environment and follow the installation directions in the cryoDRGN README precisely, in the order they are listed, and without installing anything else in this new conda environment.

When you have a clean installation, activate this new conda environment, run `jupyter lab`, open your notebook file, run all cells in order and wait until each one terminates before running the next one. Do you get the interactive figures and tables now?

**Comment by EB-kim** [comment]
Thanks for the help ,but I am currently working on a school computer and I can't create a conda environment because apparently the python version in conda environment collide with the other programs that are installed in this computer that are using different versions of python. I think I can install the jupyter extensions using pip install but I just don't know where to install them to get rid of the error. I will think more about it to resolve the problem and thanks for the help.

**Comment by michal-g** [comment]
Closing as this seems more of a user-side issue with environments — see #323 for how we resolved other chronic issues with dependencies used by interactive widgets in the Jupyter notebooks.
